### ISSUE TITLE
4.0版本遇怪卡顿掉帧角色回血功能不能用

### ISSUE THREAD

**Issue by RXYSH** [JDDKCN/KCN-GenshinServer#11]
新版本遇到怪物或战斗时掉帧严重，而且所有角色回血技能与天赋都失效了，之前3.7那个版本遇怪和战斗不会掉帧卡顿且部分角色回复功能可以使用，还有枫丹水下无法正常潜水，好像需要解锁枫丹水神像才能使用潜水功能，后续更新能优化和处理吗？

**Comment by JDDKCN** [comment]
目前的4.0服务端是Dev版本，出现各种不稳定和bug都是正常现象，后续更新将会逐渐修复。
