### ISSUE TITLE
4.0无法进行任务，gm工具连不上

### ISSUE THREAD

**Issue by Cerry233** [JDDKCN/KCN-GenshinServer#16]
![1](https://github.com/JDDKCN/KCN-GenshinServer/assets/144158363/436fd21c-e8ff-464e-94b8-de8cdb7619b5)
![2](https://github.com/JDDKCN/KCN-GenshinServer/assets/144158363/095f5e3d-2fb3-437a-b1cb-60d7722a88fa)
![3](https://github.com/JDDKCN/KCN-GenshinServer/assets/144158363/a3f32abc-391e-4185-8659-0a85aeb36b9c)
![4](https://github.com/JDDKCN/KCN-GenshinServer/assets/144158363/626229a0-593d-4476-816a-e140a4c329a7)
![5](https://github.com/JDDKCN/KCN-GenshinServer/assets/144158363/355fa87b-7a30-4bde-9f0a-74472ab6198f)
![6](https://github.com/JDDKCN/KCN-GenshinServer/assets/144158363/bd729c29-0f46-412d-a4dc-431107e6e65c)

**Comment by JDDKCN** [comment]
把控制台上的验证码输入GM工具的验证码框中，而不是向控制台输数字。

**Comment by Cerry233** [comment]
> 把控制台上的验证码输入GM工具的验证码框，而不是控制台向输出数字。

是这样啊，那没法做任务怎么办，一直提示游戏更新发生错误

**Comment by Cerry233** [comment]
主要问题是无法进行任务，是bug吗

**Comment by Cerry233** [comment]
我换成1.4.1版本的启动器就能做任务了，有什么头绪吗

**Comment by JDDKCN** [comment]
新版服务端bug，不归我管。对于你在服务端遇到的问题，请到grasscutter项目提issues。
