### ISSUE TITLE
帮我看看这是为何

### ISSUE THREAD

**Issue by StarWC** [JDDKCN/KCN-GenshinServer#18]
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/49085785/c1d6f470-8091-41f6-bb25-1be861d797f5)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/49085785/f123fef5-a8da-4e86-9eb6-f1e9db99a464)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/49085785/e6e833c0-bd80-4785-90a9-56fc3b1bb9a2)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/49085785/acee004f-8bc7-4f65-838f-98401f966793)

进游戏就卡在教程这里了，只能用GM工具强行完成任务。。

**Comment by JDDKCN** [comment]
服务端bug
