### ISSUE TITLE
您好，我使用本地模式开始游戏后，第一个任务靠近派蒙无法完成

### ISSUE THREAD

**Issue by yun-sen** [JDDKCN/KCN-GenshinServer#19]
服务端窗口有如下内容：
java.lang.NullPointerException: null
09:31:08 <ERROR:SceneScriptManager> group.monsters null for group 133217262
09:31:08 <ERROR:SceneScriptManager> group.gadgets null for group 133217262
09:31:08 <ERROR:SceneScriptManager> group.npcs null for group 133217262
09:31:08 <ERROR:SceneScriptManager> group.regions null for group 133217262

**Comment by yun-sen** [comment]
抱歉询问之前没有看到其它issues
请问我该如何更改我的gc内核？

**Comment by yun-sen** [comment]
已解决，使用release1.4.1后没有问题

**Comment by hinata2233** [comment]
请问您是如何解决的方便详细告知吗，十分感谢

**Comment by JDDKCN** [comment]
请下载最新版程序，bug已修复。
