### ISSUE TITLE
MOD工具无法使用

### ISSUE THREAD

**Issue by AidenQin** [JDDKCN/KCN-GenshinServer#26]
<img width="586" alt="屏幕截图 2023-09-20 101619" src="https://github.com/JDDKCN/KCN-GenshinServer/assets/90512094/54489dfd-7065-4dca-b776-a4e694bdf566">
选择一键注入时显示无法打开文件，请用管理员模式模式重试。
但是程序已经时管理员模式了，还是没有用。

**Comment by JDDKCN** [comment]
感谢反馈bug。我们将尝试在未来版本中解决问题。

**Comment by milozya** [comment]
可以手动打开那个程序，目前我是用这个方法解决的

**Comment by Cerry233** [comment]
俺也一样，我也是手动打开的

**Comment by JDDKCN** [comment]
bug已解决，请下载新版一键端。
