### ISSUE TITLE
游戏登录一段时间后就自动掉线，不太稳定

### ISSUE THREAD

**Issue by ssfkfffddj** [JDDKCN/KCN-GenshinServer#28]
登录游戏一段时间之后就会掉线重连，游戏中画面中心一直转圈，一会之后就自动重连了。有时候有些操作，比如说传送、切换角色，需要很长时间才会响应。
![github](https://github.com/JDDKCN/KCN-GenshinServer/assets/103518420/38f3a2fe-7eaa-4372-9707-6d3433bca777)

**Comment by JDDKCN** [comment]
服务端问题，现在的版本不稳定。
