### ISSUE TITLE
希望软件内能整合代理工具的配置

### ISSUE THREAD

**Issue by liesauer** [JDDKCN/KCN-GenshinServer#29]
一旦开了服务之后，我自己的梯子代理设置就被挤掉了，就没办法一边开着游戏，一遍上外网搜东西啥的，连gamebanana都上不去。

**Comment by JDDKCN** [comment]
这个没办法，程序必须设置系统代理才能正确的代理客户端流量。你可以尝试使用手机或其他设备翻墙。
