### ISSUE TITLE
網路報錯

### ISSUE THREAD

**Issue by captainstyles** [JDDKCN/KCN-GenshinServer#3]
服務端與數據庫都正常開啟，但是進入遊戲後會出現網路錯誤，測試連結也是正常的，是否是因為版本不符的關係呢?
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/61380579/132edefe-369c-498d-b4c1-0226be5e2864)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/61380579/af4cc3ef-3e16-4934-9e21-989fe2f4ee7c)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/61380579/77c36612-dc22-4cf8-8cc8-c7e4af00c1ca)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/61380579/78a83774-ffcc-4124-a1dd-db5391917cff)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/61380579/d2b7416c-8253-4262-b3d5-8f379516e4aa)

**Comment by JDDKCN** [comment]
是的，请使用更新的服务端版本，支持了4.0.
