### ISSUE TITLE
报告问题

### ISSUE THREAD

**Issue by CoCoSuYa** [JDDKCN/KCN-GenshinServer#30]
1.剧情走到蒙德城过完风魔龙从骑士团出门后，大部分npc处于惊吓状态无法交互，关闭游戏重新进入也一样
2.爆率和冒险等级提升数据异常，打普通木箱会爆非常多食材，开宝箱出宝率也异常高(骑士团楼顶的一个宝箱甚至出双金弓)，冒险等级提升时会出现一个非常大数值的冒险经验增加，但是实际上只增加了几百点
3.GCTool加载活动和卡池数据异常，加载活动会显示活动已结束(即使活动还在有效期)，加载诺埃尔卡池时数据展示异常
4.卡池不能直接将原石转换成相遇/纠缠之缘

5.商店空白(已解决)
解决办法：
找到压缩包在server/grasscutter/GC-Resources-4.0.zip，然后在压缩包里面的Resource/ExcelBinOutput找到文件ShopGoodsExcelConfigData.json，将json文件解压后改名为Shop.json，替换掉Server下的Shop.json文件，不过这样改完后商城里的商品会变得很奇怪，需要通过GC进一步修改Shop.json里的商品，建议还是等grasscutter修好后更新

**Comment by CoCoSuYa** [comment]
第一个问题发现是我蠢了，剧情就是npc无法交互的，需要继续做任务
2345是存在的问题

**Comment by lukegrapery** [comment]
> 1.剧情走到蒙德城过完风魔龙从骑士团出门后，大部分npc处于惊吓状态无法交互，关闭游戏重新进入也一样 2.爆率和冒险等级提升数据异常，打普通木箱会爆非常多食材，开宝箱出宝率也异常高(骑士团楼顶的一个宝箱甚至出双金弓)，冒险等级提升时会出现一个非常大数值的冒险经验增加，但是实际上只增加了几百点 3.GCTool加载活动和卡池数据异常，加载活动会显示活动已结束(即使活动还在有效期)，加载诺埃尔卡池时数据展示异常 4.卡池不能直接将原石转换成相遇/纠缠之缘
> 
> 5.商店空白(已解决) 解决办法： 找到压缩包在server/grasscutter/GC-Resources-4.0.zip，然后在压缩包里面的Resource/ExcelBinOutput找到文件ShopGoodsExcelConfigData.json，将json文件解压后改名为Shop.json，替换掉Server下的Shop.json文件，不过这样改完后商城里的商品会变得很奇怪，需要通过GC进一步修改Shop.json里的商品，建议还是等grasscutter修好后更新


有关商店空白，已经照您写的替换档案，但重启server后进入游戏依然还是空白的，请问是少做了什么步骤吗?
