### ISSUE TITLE
使用基础版本无法进入私服

### ISSUE THREAD

**Issue by KohigashiHitona** [JDDKCN/KCN-GenshinServer#31]
启动游戏直接进入官服，是不是因为游戏版本更新到了4.1.0？要等私服端更新？
<img width="737" alt="image" src="https://github.com/JDDKCN/KCN-GenshinServer/assets/102724719/41284c26-1549-4d43-b852-dac3046b9282">
<img width="734" alt="image" src="https://github.com/JDDKCN/KCN-GenshinServer/assets/102724719/956bab60-e113-4f7a-b1b3-b3de025f43d4">

**Comment by JDDKCN** [comment]
看不见程序里，readme里和服务端里的适用版本是4.0.x吗？
