### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by diillb** [JDDKCN/KCN-GenshinServer#32]
应该是代理没运行。安装ca证书时，防火墙弹窗问代理用公共还是家庭网络，我两个都没选直接给拒绝了，现在想找都找不到，重安装ca证书也不弹，就算我不结束服务也能正常上网。大佬救救！

**Comment by diillb** [comment]
去防火墙将代理加入私有网络，还是一样的结果
![12](https://github.com/JDDKCN/KCN-GenshinServer/assets/128363088/b7a219b6-92b7-4c3f-95a5-46577a12adf3)
![13](https://github.com/JDDKCN/KCN-GenshinServer/assets/128363088/5f402c43-67ef-4666-9216-6cc71161fbc7)
![14](https://github.com/JDDKCN/KCN-GenshinServer/assets/128363088/eefa21d2-21d6-4e89-b021-05a79082c1c4)
![15](https://github.com/JDDKCN/KCN-GenshinServer/assets/128363088/f311ed52-416d-4024-918a-2a65630e32c0)
![16](https://github.com/JDDKCN/KCN-GenshinServer/assets/128363088/073cb93b-c0d3-431a-afd4-14890f81f8fa)

**Comment by JDDKCN** [comment]
大哥，你用4.0的端带4.1？看不见到处标的支持版本4.0.x？

**Comment by Flolady** [comment]
服务端只支持4.0.1的，你这个应该是刚更新了4.1.0
