### ISSUE TITLE
新版本Grasscutter我可以自己更新吗，是直接替换到文件夹里就行吗

### ISSUE THREAD

**Issue by Cerry233** [JDDKCN/KCN-GenshinServer#33]
我可以自己换文件吗，就是把原来的删了放新的进去，我在你Server文件夹里找到了grasscutter的文件，我直接换就行吗，还是说等你的更新

**Comment by lukegrapery** [comment]
> 可以直接换

可以请教具体要替换哪些档案吗？謝謝！

**Comment by JDDKCN** [comment]
> > 可以直接换
> 
> 可以请教具体要替换哪些档案吗？謝謝！

你可以替换 `./Server/grasscutter/grasscutter.jar` 为你构建的版本，也可以在 `设置选项卡-替换服务端启动版本` 中，选择你自己的服务端(需要包括Res等)。
