### ISSUE TITLE
过程中发现的一些BUG

### ISSUE THREAD

**Issue by CoZuAn** [JDDKCN/KCN-GenshinServer#35]
环境：  
系统是WINDOS 10 ,使用的一键端版本是V0.1.6BETA 09.14版本
系统资源对于该软件的使用而言有足够的冗余。

1.剑冢封印解锁，三个解锁中挑战擂台的计时挑战无法完成，跟官服相比，缺少在开始挑战之后出现的屏障和打完第一波怪物不会出现后续的怪物。与深渊螺旋的第一关挑战类似。（三个挑战中，无法解锁的挑战为好肉族封印，对应的解封任务为42201，不过在使用后，虽然有演出动画，可是封印实际并未解锁）

2.在进入对应城邦的声望相关任务和奖励界面的时候，会出现卡住现象，需要退出重新登陆游戏可解决卡住问题。（目前仅测试蒙德）。

3.在传说任务卢皮卡系列任务中，进行到挑战北风之狼的时候，任务无法召唤出需要战斗的对象，任务链中断。（该任务ID为45405）
4.由任务《导光仪式》（ID是39003开始），需要解除风龙废墟封印无法正常进行。无法解除导光机关的红色封印圈，所以无法将拾取的部件放入对应槽位，同时没有携带部件时候的特效演出。

5.任务ID为39402的击败特瓦林，在一轮攻击后，BOSS消失，卡在对应的战斗场景。

目前发现失效的任务中，好似只要是需要召唤怪物出来的和需要多次切换场景的，都容易出问题。还有就是好些计时战斗的场景，计时时长都是0，貌似没有数据。

感谢作者的制作和共享，祝节日愉快。

**Comment by stefanyoung** [comment]
请问客户端更新到4.1了怎么有游玩呢？
