### ISSUE TITLE
无法进入

### ISSUE THREAD

**Issue by Tianqiangel888** [JDDKCN/KCN-GenshinServer#36]
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/96581843/0b74edc8-3896-46db-8f50-22294477b54d)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/96581843/eebfd14f-469a-494f-aa52-3331bb9d34bc)
无法进入服务器，报错，还望路过大佬指点一下，在下感激不尽

**Comment by CoZuAn** [comment]
就我遇到这个问题的解决方法是换客户端
服务端支持的是4.0.X，而如果你用的是现在的客户端那就是会出现这个报错。
具体下载的方式，你可以找B站，搜索专栏，关键字“原神下载链接”，可以找到对应链接。

**Comment by JDDKCN** [comment]
大哥，你用4.0的端带4.1？看不见到处标的支持版本4.0.x？
