### ISSUE TITLE
啟動服務端報錯以及連接失敗問題

### ISSUE THREAD

**Issue by yotv2000tw** [JDDKCN/KCN-GenshinServer#4]
```Error loading file 'GC-Resources-4.0/Resources/ExcelBinOutput/GivingExcelConfigData.tsj' - File does not exist. You are missing resources. Note that this file may exist in JSON, TSV, or TSJ format, any of which are suitable.```
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/51760140/18f18b90-31e3-403c-98b2-777e8f695488)
其中也包含```00:47:46 <WARN:FileUtils> Failed to read resource: /html/handbook.html```的報錯
想請問這個報錯怎麼解決。

以及在經過連線測試正常後，進入後輸入使用者名稱以及密碼後，直接跳出「連接失敗」，是與前面這個問題有關，還是另有設置問題導致，感謝。
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/51760140/5fe7f4ae-3490-41b6-a350-e347e67b09db)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/51760140/33c17fc9-f8d1-4bcb-a320-48e20a915d4e)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/51760140/59f189b8-93fd-47f7-a338-bb1d4a71cde7)
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/51760140/fc731eb0-5033-43d6-87c1-59aa55b689bc)

OS: Windows 11

**Comment by JDDKCN** [comment]
根据描述，大概率是代理问题。请检查代理端口是否有占用，代理进程是否正常开启，CA证书是否安装。

**Comment by GalileoFe** [comment]
删除文件夹，重启电脑，重新解压文件夹就修好了。
