### ISSUE TITLE
一个关于证书的疑问

### ISSUE THREAD

**Issue by pen098** [JDDKCN/KCN-GenshinServer#41]
该工具首次启动的时候，不是会要求安装一个CA证书的吗？我在清除一些已安装的CA证书时，把工具安装的CA证书误删了，但再次启动的时候也没要求我重新安装，而且在左上角的选项中选取手动安装CA证书，也会显示证书已安装，这是咋回事？是我没删干净，还是其实没有证书也能用的？要如何才能重新安装证书呢？因为我在这之后也过打开游戏，尝试了几次后，发现主要问题是新账号开局选择双子之一然后设定人物名字时候好像无法确认，得直接关掉游戏再进才能继续。

**Comment by JDDKCN** [comment]
CA证书是和代理相关的东西，没有CA证书，你将无法进入游戏。如果启动器没有提示安装CA证书，那就是证书存在且正确配置了。你描述的问题是服务端bug，和代理/CA证书无关。
