### ISSUE TITLE
商城无法正常读取

### ISSUE THREAD

**Issue by GalileoFe** [JDDKCN/KCN-GenshinServer#5]
![image](https://github.com/JDDKCN/KCN-GenshinServer/assets/138156577/9900aec0-1fab-4534-838b-872706f65d98)
如图。
已查看/Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json文件，是正常的。服务端没有报错。

**Comment by JDDKCN** [comment]
如果发现什么功能用不了或者不好使的话，都是目前bug的，很正常，可能下次更新就修复了。
