### ISSUE TITLE
网络错误无法解决

### ISSUE THREAD

**Issue by wdasdfghjkl** [JDDKCN/KCN-GenshinServer#50]
<img width="464" alt="网络出错" src="https://github.com/JDDKCN/KCN-GenshinServer/assets/145345511/fd2c6320-c118-4665-ab4e-c4a5ed44ded7">
这种问题怎么解决，求帮帮！

**Comment by JDDKCN** [comment]
代理问题。请结束服务后更改默认端口，重新运行服务。
