### ISSUE TITLE
聊天窗无法输入指令，没有会话对象

### ISSUE THREAD

**Issue by NordlichtS** [JDDKCN/KCN-GenshinServer#6]
以前的割草机在游戏内聊天窗会有一个会话对象，类似好友，可以用于直接输入指令（和GC TOOLS 里的指令相同）但现在这个功能似乎没有了？添加会话对象也会显示根本没有好友。是功能删掉了吗，还是缺少赋予权限之类的操作？

**Comment by JDDKCN** [comment]
目前是bug的，还没修
