### ISSUE TITLE
左键异常（无法攻击），但其他行为正常并且解锁账号权限时出错

### ISSUE THREAD

**Issue by yige-yigeren** [JDDKCN/KCN-GenshinServer#8]
左键我不知道为什么（）
无法执行命令：
解锁权限的出错代码：
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at KCNServer.APICommand.APICommand_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at Sunny.UI.UIForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KCN-GenshinServer_GC一键端
    Assembly Version: 0.1.4.1
    Win32 Version: 0.1.4.1
    CodeBase: file:///E:/KCN-GenshinServer/KCN-GenshinServer_GC%E4%B8%80%E9%94%AE%E7%AB%AF.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SunnyUI
    Assembly Version: 3.3.9.0
    Win32 Version: 3.3.9.0
    CodeBase: file:///E:/KCN-GenshinServer/SunnyUI.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///E:/KCN-GenshinServer/Newtonsoft.Json.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
SunnyUI.Common
    Assembly Version: 3.3.9.0
    Win32 Version: 3.3.9.0
    CodeBase: file:///E:/KCN-GenshinServer/SunnyUI.Common.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Configuration.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Configuration.DLL
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Configuration.Json.DLL
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Configuration.EnvironmentVariables.DLL
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly Version: 7.0.0.4
    Win32 Version: 7.0.423.11508
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Configuration.Binder.DLL
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Primitives.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.FileProviders.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.Configuration.FileExtensions.DLL
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.FileProviders.Physical.DLL
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/Microsoft.Extensions.FileSystemGlobbing.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///E:/KCN-GenshinServer/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///E:/KCN-GenshinServer/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.51805
    CodeBase: file:///E:/KCN-GenshinServer/System.Text.Json.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///E:/KCN-GenshinServer/System.Buffers.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///E:/KCN-GenshinServer/System.Numerics.Vectors.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by JDDKCN** [comment]
感谢提供bug。你可以先尝试使用另一种方法解锁账号权限。不能攻击仅限于主角处于无元素状态下，解锁七天神像后获得风元素力即可恢复正常。

**Comment by yige-yigeren** [comment]
> 感谢提供bug。你可以先尝试使用另一种方法解锁账号权限。不能攻击仅限于主角处于无元素状态下，解锁七天神像后获得风元素力即可恢复正常。

哦哦，谢谢。

**Comment by yige-yigeren** [comment]
> 感谢提供bug。你可以先尝试使用另一种方法解锁账号权限。不能攻击仅限于主角处于无元素状态下，解锁七天神像后获得风元素力即可恢复正常。

另一种方法是？没找到@.@

**Comment by JDDKCN** [comment]
- **GM工具问题**：你没有权限执行此命令。
  - 快捷方法：
  1. 请在一键端设置选项卡-解锁账号权限输入你要解锁的UID，账号即开放所有权限。
  - 其它方法：
  1. 请在GM工具中点击"管理"选项，在权限管理一栏中，输入你目前账号的UID，选择 `*` (开放该账号所有权限)，点击添加。
  2. 请把生成的命令复制到服务端的命令行窗口中，回车执行。这样，你的账号就可以使用所有命令了。【服务端不是GM工具，是黑色的命令提示符窗口】
  3. 你也可以直接输入以下命令(在服务端窗口内)：permission add @10001 * 【10001处换为你的UID】。
